
ignore_list = [
    "Hello recv from server",
    " No entries ",
    "USB disconnect",
    "Is a desktop session",
    "Checking session /org/freedesktop",
    "Loop exited. Forcing reload",
    "onedrive",
    "Finished apt-daily.service",
    "message repeated",
    "CCMP_REPLAY",
    "BA_FLUSH",
    "USB hub found",
    "unknown client",
    "DHCPREQUEST",
    "DHCPACK",
    "DHCPOFFER",
    "Note that yum will try to contact the repo. when it runs most commands",
    "snapd-desktop", # bit brutal - but it spams like hell
    "Starting ISC DHCPv4 server",
    "Internet Systems Consortium DHCP Server",
    "Copyright 2004-2018 Internet Systems Consortium",
    "All rights reserved",
    "Stopping LSB: DHCP server",
    "Dormant child reaped",
    "systemd[1]: Reloading",
    "Cleanup of Temporary Directories",
    "gnome-shell",
    "gdm-x-session",
    "usbmuxd",
    "Starting System Logging Service",
    "Reached target",
    "gsd-media-keys",
    "GNOME",
    "gnome-session-binary",
    "Starting Virtual filesystem",
    "Successfully activated service",
    "Starting Accessibility",
    "Started Path",
    "reused old ethernet address",
    "arpwatch: flip flop",
    "Starting rsyslog.service",
    "tracker-miner-f",
    "tracker-store",
    "Starting Tracker metadata",
    "kubelet",
    "org.freedesktop.ScreenSaver.GetActive",
    "DHCPINFORM",
    "DHCPNAK",
    "Stopped Network Time Synchronization",
    "speech-dispatcher",
    "libreoffice",
    "Message of the Day",
    "treated changed event as add",
    "Logitech",
    " boltd",
    "not supported by any plugin",
    "ipheth",
    "iPhone USB",
]

regex_ignore_list = [
    r'Catalog compiled by \S+',

    r'kernel.+hub.+detected',
    r'kernel.+usb.+Product',
    r'(?i)lab.+usb',
    r'kernel:.+\[\s+[0-9]\.[0-9]',
    r'snapd-desktop-i.+Checking session',
    r'snapd-desktop-i.+Forcing a reload.',
    r'puppet-agent.+Requesting catalog from',
    r'puppet.+Building dependency tree',
    r'puppet-agent.+executed successfully',
    r'hid-generic .+ USB HID .+Mouse',
    r'kernel: .+ Keyboard',
    r'kernel: .+ usb.+SerialNumber',
    r'Copyright.+Internet Systems Consortium',
    r'rngd.+stats:', # rngd stats spam
    r'ADDRCONF\(NETDEV_UP\): .+ link is not ready', # IPv6 spam
    r'DAD attempt detected for .+ on .+', # more IPv6 spam (Duplicate Address Detection)
    r'puppet-agent.+Applied catalog in.+seconds',
    r'puppet-agent.+Reading state information',
    r'sshd.+Close session',
    r'lab.+kernel',
    r'lab.+dbus',
    r'lab.+os-prober',
    r'kernel:\s+usb.+(new|New) USB',
    r'kernel:\s+usb.+(removed|Removed|Manufacturer|Product:|SerialNumber|disconnect)',
    r'kernel: .+input:.+HID.+ as ',
    r'kernel: .+ KCS in invalid state', # KCS = Keyboard Controller Style (so says gpt)
    r'run-docker-runtime.+Succeeded',
    r'dhcpd.+Server starting service',
    r'x2go.+(succeeded|success)',
    r'dbus.+[Aa]ctiv',
    r'dbus-daemon.+(requested|activated)',
    r'isc-dhcp-server.+Stopping',
    r'systemd.+([Ss]tart|[Rr]each|[Ll]isten|[Ss]topped|[Ss]ucceeded)',
    r'systemd.+GnuPG',
    r'NetworkManager.+(requested_interface_mtu|requested|option|<info>)',
    r'rsyslogd.+(groupid|userid).+changed',
    r'rsyslogd.+(Acquired|start)',
    r'systemd.+Deactivated successfully',
    r'containerd.+(clean|ignoring|loading plugin|disconnected)',
    r'dockerd.+ignoring event',
    r'named.+received from primary',
    r'systemd-logind.+(logged out|Removed session)',
    r'docker.+Succeeded',
    r'snapd-desktop.+theme',
    r'kernel:\s\[\s\s\s+[0-9]',
    r'dnsmasq.+\sread\s',
    r'kernel:.+usb.+(new|New)',
    r'kernel: hub.+(found|attached|detected)',
    r'pcieport.+(bridge|released|assigned)',
    r'firefox.+info',
    r'dockerd.+NetworkDB stats',
    r'enx[0-9a-f]{6}.+renamed',
    r'apt-daily\.service .+ unmet condition check.+ConditionACPower',
    r'For info, please visit.+dhcp',
    r'dhcpd.+Wrote.+ leases to leases file.',
    r'kernel.+usb .+Manufacturer',
    # ELK-era estate noise (tuned on the 2026-08-26 dump). The anomaly
    # detectors run on the RAW lines upstream of this filter, so volume
    # changes in any of these still get flagged; this only keeps them
    # away from the LLM issue path.
    r"named\[\d+\]: client .+ denied",                     # scanners probing an authoritative DNS box
    r"named\[\d+\]: client .+ query failed \(REFUSED\)",   # the REFUSED twin of every denied line
    r"named\[\d+\]: .*rate limit (slip|drop)",             # response-rate-limiting doing its job
    r"CROND?\[\d+\]: \([^)]+\) (CMD|LIST)",                # cron ran a job / listed a crontab
    r"CRON.+No MTA installed",
    r"crontab\[\d+\]: \([^)]+\) LIST",
    r"dhclient\[\d+\]: XMT: Solicit",                      # DHCPv6 solicit heartbeat
    r"ocsinventory-agent.+\[debug\]",
    r"puppet-agent.+Testing connection with",              # Defender connectivity self-check
    r"systemd.+Closed ",
    r"systemd-logind.+New session",
    r"Got notification message from PID",                  # mdatp systemd notify chatter
    r"nfsrahead.+setting .+ readahead",
    r"named\[\d+\]: (stop limiting|limit REFUSED) error responses",  # RRL start/stop announcements
    r"systemd\[\d+\]: .+ Consumed .*CPU time",             # per-service resource accounting
    r"nessus-service.+Killing nessusd",                    # nessus agent's scheduled restart
    r"rpc\.mountd.+client (attached|detached)",            # routine NFS mounts
]

normalise_map = [
    (r"snap-store.+not handling", "snap-store not handling"),
    (r"acvpndownloader_major", "acvpndownloader_major"),
    (r"acvpndownloader_minor", "acvpndownloader_minor"),
    (r"pulseaudio.+segfault", "pulseaudio segfault"),
    (r"setroubleshoot.+SELinux", "setroubleshoot: SELinux"),
    (r"gnome-shell.+DBusError", "gnome-shell DBusError"),
    (r"CCMP.+REPLAY", "CCMP_REPLAY"),
    (r"BA.+FLUSH", "BA_FLUSH"),
    (r'snapd-desktop.+Failed to do gtk init', 'snapd Failed to do gtk init'),
    (r'snapd-desktop-integration.+no authorization protocol specified', 'snapd no authorization protocol specified'),
    (r'snapd-desktop-integration.+Checking session', 'snapd Checking session'),
    (r'snapd-desktop-i.+Forcing a reload', 'snapd Forcing a reload'),
    (r"FLUSH.+DEAUTH", "FLUSH_DEAUTH"),
    (r'xs_tcp_setup_socket: connect returned unhandled error', 'xs socket error'),
    (r"service=registry", "docker service=registry"),
    (r"snap-store.+not handling", "snap-store not handling"),
    (r"xrdp", "xrdp"),
    (r"puppet-agent.+(Could not|Failed|Unable|failed)", "puppet-agent Error"),
    (r"InRelease", "InRelease Error"),
    (r"audit.+DENIED", "audit DENIED"),
    (r'(acvpnui|acwebhelper|acvpndownloader|acvpnagent)', "acvpnui (CISCO VPN)"),
    (r"puppet.+ensure changed.+corrective", "puppet ensure changed corrective"),
    (r"snap.+store.+error", "snap-store error"),
    (r"systemd.+run-docker-runtime", "systemd run-docker-runtime"),
    (r"Started snap", "Started snap"),
    (r"snap.canonical.*Succeeded", "snap.canonical Succeeded"),
    (r'nagios: wproc:.+early_timeout=1; exited_ok=0; wait_status=0; error_code=62', 'nagios early_timeout'),
    (r'kernel:.+ Code: ', 'kernel crash or segfault debug info'),
    (r'nagios: Warning: Check of host.+timed out', 'nagios host check timed out'),
    (r'puppet nagios: wproc.+service=\(null\)', 'puppet service=null'),
    (r'nagios:.+read.+ returned error', 'nagios read error'),
    (r'nagios:.+wproc:.+early_timeout=1', 'nagios core worker early timeout'),
    (r'nagios.+CHECK job .+ timed out', 'nagios check job timed out'),
    (r'puppet-agent.+Unable to locate package', 'puppet-agent unable to locate package'),
    (r'puppet-agent.+no installation candidate', 'puppet-agent no installation candidate'),
    (r'puppet-agent.+returned 100: Reading package lists', 'puppet-agent apt update failed'),
    (r'puppet.+Service.+failed dependencies', 'puppet service failed dependencies'),
    (r'puppet.+Journal begins at', 'puppet journal begins at'),
    (r'puppet.+not available', 'puppet package not available'),
    (r'puppet-agent.+No more mirrors to try', 'puppet-agent no more mirrors to try'),
    (r'puppet-agent.+Could not retrieve catalog', 'puppet-agent could not retrieve catalog'),
    (r'puppet-agent.+Errors were encountered while processing', 'puppet-agent errors encountered while processing'),
    (r'puppet-agent.+running.+failed', 'puppet-agent failed to start service on a client'),
    (r'sshd.+Connection closed.+preauth', 'sshd connection closed preauth'),
    (r'wproc:.+timed out', 'nagios core worker timed out'),
    (r'wproc:.+timeout', 'nagios core worker timeout'),
    (r'setroubleshoot: SELinux is preventing .+ from .+', 'setroubleshoot SELinux is preventing access (natch)'),
    (r'setroubleshoot.+failed to retrieve rpm info', 'setroubleshoot failed to retrieve rpm info'),
    (r'/var/run/anydesk.pid', 'anydesk pid file'),  # weird anydesk spam
    (r'no free leases', 'dhcp no free leases'),
    (r'dhcpd.+DHCPDISCOVER.+via', 'regular dhcpd DHCPDISCOVER'),
    (r'pulseaudio segfault', 'pulseaudio segfault'),
    (r'nf_conntrack.+full', 'nf_conntrack full'),
    (r'snap has no updates available', 'snap has no updates available'),
    (r'xs socket error', 'xs socket error'),
    (r'puppet-agent Error get lock', 'puppet-agent Error get lock'),
    (r'nagios.+check.+timed out', 'nagios check timed out'),
    (r'It is held by process', 'It is held by process'),
    (r'No Presto metadata', 'puppet No Presto metadata'),
    (r'New session.+user root', 'New session user root'),
    (r'puppet-agent.+held by process', 'puppet-agent held by process'),
    (r'Consecutive tx fail', 'Consecutive tx fail'),
    (r'sshd.+from', 'ssh login'),
    (r'OnCloseSessionDone error', 'OnCloseSessionDone error'),
    (r'UFW BLOCK', 'UFW BLOCK'),
    (r'chronyd.+replaced', 'chronyd changed timeserver'),
    (r'mtp-probe: checking bus', 'mtp-probe checking bus'),
    (r'dhcpd.+is duplicate', 'dhcpd is duplicate'),
    (r'smartd.+POWER', 'smartd POWER'),
    (r'dhcp6_dump.+No such file or directory', 'dhcp6_dump No such file or directory'),
    (r'dhcp_dump.+No such file or directory', 'dhcp_dump No such file or directory'),
    (r'dhcpd.+Wrote 0', 'dhcpd Wrote 0 hosts'),
    (r'puppet-agent.+ensure', 'puppet-agent ensure'),
    (r'Launching IPv4 server only', 'dhcpdLaunching IPv4 server only'),
    (r'puppet-agent.+:$', 'puppet-agent empty log line'),
    (r'unknown option: denyinterface', 'dhcpd unknown option: denyinterface'),
    (r'puppet-agent.+has failures: true', 'puppet-agent has failures: true'),
    # A busy resolver SERVFAILs all day for broken remote zones; keep the
    # fact visible (dedupe caps it at 3 lines) but drop the per-query detail.
    (r'named\[\d+\]: client .+ query failed \(SERVFAIL\)', 'named SERVFAIL query failure'),
    (r'simplesamlphp.+is now using namespaces', 'simplesamlphp legacy class name deprecation warning'),
]
